/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sig.views;

import com.sig.controller.InvoiceController;
import com.sig.models.Invoice_Header;
import com.sig.models.Invoice_Header_Table;
import com.sig.models.Invoice_Line;
import com.sig.models.Invoice_Lines_Table;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author HP
 */
public class InvoiceForm extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_2 = new javax.swing.JMenuItem();
        Item = new javax.swing.JMenuItem();
        Button_1 = new javax.swing.JScrollPane();
        I_invoices = new javax.swing.JTable();
        I_invoices.getSelectionModel().addListSelectionListener(this);
        Create_Invoice = new javax.swing.JButton();
        Button_2 = new javax.swing.JScrollPane();
        Invoice_Details = new javax.swing.JTable();
        Invoice_Number = new javax.swing.JLabel();
        Invoice_Date = new javax.swing.JLabel();
        Customer_Name_Button = new javax.swing.JLabel();
        Total_Invoice = new javax.swing.JLabel();
        I_invoive_Number = new javax.swing.JLabel();
        invoicedate = new javax.swing.JLabel();
        customer_button = new javax.swing.JLabel();
        Invoice_Total = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        To_Cancel = new javax.swing.JButton();
        To_Delete_Invoice = new javax.swing.JButton();
        Menu_1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Load_File = new javax.swing.JMenuItem();
        Save_File = new javax.swing.JMenuItem();

        Menu_2.setText("jMenuItem1");

        Item.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        I_invoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Button_1.setViewportView(I_invoices);

        Create_Invoice.setText("Create New Invoice");
        Create_Invoice.addActionListener(actionListener);

        Invoice_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Button_2.setViewportView(Invoice_Details);

        Invoice_Number.setText("Invoice Number");

        Invoice_Date.setText("Invoice Date");

        Customer_Name_Button.setText("Customer Name");

        Total_Invoice.setText("Invoice Total");

        Save.setText("Save");
        Save.addActionListener(actionListener);

        To_Cancel.setText("Cancel");
        To_Cancel.addActionListener(actionListener);

        To_Delete_Invoice.setText("Delete Invoice");
        To_Delete_Invoice.addActionListener(actionListener);

        Menu.setText("File");

        Load_File.setText("Load File");
        Load_File.addActionListener(actionListener);
        Menu.add(Load_File);

        Save_File.setText("Save File");
        Save_File.addActionListener(actionListener);
        Menu.add(Save_File);

        Menu_1.add(Menu);

        setJMenuBar(Menu_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Customer_Name_Button)
                                .addComponent(Total_Invoice, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Invoice_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Invoice_Number))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(I_invoive_Number)
                            .addComponent(invoicedate)
                            .addComponent(customer_button)
                            .addComponent(Invoice_Total)))
                    .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Create_Invoice)
                .addGap(40, 40, 40)
                .addComponent(To_Delete_Invoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(115, 115, 115)
                .addComponent(To_Cancel)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Invoice_Number)
                            .addComponent(I_invoive_Number))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Invoice_Date)
                            .addComponent(invoicedate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Customer_Name_Button)
                            .addComponent(customer_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total_Invoice)
                            .addComponent(Invoice_Total))
                        .addGap(40, 40, 40)
                        .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To_Delete_Invoice)
                    .addComponent(Create_Invoice)
                    .addComponent(Save)
                    .addComponent(To_Cancel))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Load_File;
    private javax.swing.JMenuItem Save_File;
    private javax.swing.JButton To_Cancel;
    private javax.swing.JButton Create_Invoice;
    private javax.swing.JLabel Customer_Name_Button;
    private javax.swing.JLabel customer_button;
    private javax.swing.JButton To_Delete_Invoice;
    private javax.swing.JLabel Total_Invoice;
    private javax.swing.JLabel Invoice_Date;
    private javax.swing.JTable Invoice_Details;
    private javax.swing.JLabel Invoice_Number;
    private javax.swing.JLabel Invoice_Total;
    private javax.swing.JLabel invoicedate;
    private javax.swing.JTable I_invoices;
    private javax.swing.JLabel I_invoive_Number;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar Menu_1;
    private javax.swing.JMenuItem Menu_2;
    private javax.swing.JMenuItem Item;
    private javax.swing.JScrollPane Button_1;
    private javax.swing.JScrollPane Button_2;
    private javax.swing.JButton Save;
    // End of variables declaration//GEN-END:variables
    private InvoiceController actionListener=new InvoiceController(this);
    private ArrayList<Invoice_Header> invoicesArray;
    private ArrayList<Invoice_Line> invoiceLinesArray;
    private Invoice_Header_Table headerTableModel;
    private Invoice_Lines_Table linesTableModel;
   
    public static SimpleDateFormat date=new SimpleDateFormat("dd-MM-yyyy");

    public Invoice_Lines_Table getLinesTableModel() {
        return linesTableModel;
    }

    public void setLinesTableModel(Invoice_Lines_Table linesTableModel) {
        this.linesTableModel = linesTableModel;
    }
    
    
    public void setInvoicesArray(ArrayList<Invoice_Header> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    
    public Invoice_Header getInvCode(int code){
    
        for(Invoice_Header inv:invoicesArray){
            if(inv.getInvoice_Number()==code){
            
                return inv;
            }
        }
        return null;
    }  

    public Invoice_Header_Table getHeaderTableModel() {
        return headerTableModel;
    }
    
    public void setHeaderTableModel(Invoice_Header_Table headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public JTable getInvoice_Details() {
        return Invoice_Details;
    }

    public JTable getI_invoices() {
        return I_invoices;
    }

    public InvoiceController getActionListener() {
        return actionListener;
    }

    public ArrayList<Invoice_Header> getInvoicesArray() {
        return invoicesArray;
    }

    public ArrayList<Invoice_Line> getInvoiceLinesArray() {
        return invoiceLinesArray;
    }

    public void setInvoiceLinesArray(ArrayList<Invoice_Line> invoiceLinesArray) {
        this.invoiceLinesArray = invoiceLinesArray;
    }
    
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        //System.out.println("selection listener");
        selectRowFromInvoices();
    }

    private void selectRowFromInvoices() {
       
        int selectedRow= I_invoices.getSelectedRow();
        
        if(selectedRow>=0){
        Invoice_Header row = headerTableModel.getInvoices().get(selectedRow);
        ArrayList<Invoice_Line> lines=row.getLines();
        setInvoiceLinesArray(lines);
        linesTableModel=new Invoice_Lines_Table(lines);
        Invoice_Details.setModel(linesTableModel);
        linesTableModel.fireTableDataChanged();
        customer_button.setText(row.getCustomer_Name());
        I_invoive_Number.setText(""+row.getInvoice_Number());
        Invoice_Total.setText(""+row.Sum_of_Lines());
        invoicedate.setText(InvoiceForm.date.format(row.getInvoice_Date()));
       
        
        }
        
    }

    public JLabel getCustomer_button() {
        return customer_button;
    }

    public JLabel getInvoice_Total() {
        return Invoice_Total;
    }

    public JLabel getInvoicedate() {
        return invoicedate;
    }

    public JLabel getI_invoive_Number() {
        return I_invoive_Number;
    }
    
    
    }






